### PR TITLE
Add a form for updating the password in preference page

### PR DESCRIPTION
**Pull request by Hakimba**
This PR adds the possibility to change your password on the preference page, in another form.

### CODE REVIEW

**Review by gr-im — CHANGES_REQUESTED** [review]
Changing the password is a sensitive action, so I think that as for the creation of the account, there should be a confirmation field, you can take inspiration from what has been done in the insertion of a new user.

**Comment by Hakimba** [comment]
@gr-im I added the confirmation field

**Comment by gr-im** [comment]
If `ocamlformat` was applied, I'll very happy to merge when the CI will be green. Thanks a lot!

**Review by gr-im — APPROVED** [review]

**Comment by gr-im** [comment]
@xvw May I hask for a deployment?

**Pull request merged**
