### PR TITLE
Fix the date of publication from UTC+2 UTC+1

### PR DESCRIPTION
**Pull request by leonard-IMBERT**
This is a hardfix of #61, waiting for a more complete fix.

### CODE REVIEW

**Comment by gr-im** [comment]
Thank you very much for your contribution.
As you mentioned in #61, I think the best approach would be to allow the user to define, via their profile, their timezone offset. As far as this fix is concerned, I must admit that I am not very enthusiastic about it.
I am not at all opposed to a _quick-fix_. But I think it should be a little less brutal. A good approach, in my opinion, would be to use the current date to define the offset to be added. This would require considering that **everyone is on the same timezone**, but it seems less radical than invalidating dates in the past. Using [this library](https://github.com/daypack-dev/timere) seems a good fit. WDYT?

**Comment by leonard-IMBERT** [comment]
I agree that this fix is a bit brutal. I will gladly add a timezone selection in the user profile but I need to dive a bit more in the source to understand everything that must be done. For now I think its:
 - Add column to the user table (new migration script, smt like `14-add-timezone-for-user`)
 - Add a field in the profile page
 - Update displayed date accordingly
 - Write tests
@gr-im am I missing something ?

I'll push an update with your solution, I've found [this reference about timezone change](https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX%3A32000L0084) that will help

**Comment by gr-im** [comment]
> @gr-im am I missing something ?

The database modification process may seem a bit complicated at first, so don't hesitate to use Slack (or Muhokama) to ask questions.

**Review by xhtmlboi — DISMISSED** [review]

**Comment by xhtmlboi** [comment]
Even the patch is not controversial. I suggest to add some tests ;)

**Comment by gr-im** [comment]
> Indeed timere seems to implement those features but after discussing with @xvw the consensus was that the library is too heavy for the usage we have right now.

Very nice! Thanks! 
As mentionned by @xhtmlboi, I think that the patch deserves some tests!

**Comment by leonard-IMBERT** [comment]
I've added some test with date I picked randomly.

Don't now if I should add test at the edge case (tz change -1s -> +1s), scan 10 years worth of date or if these dates are sufficient.

**Comment by xhtmlboi** [comment]
Sufficient from my POV!

**Review by xhtmlboi — APPROVED** [review]

**Review by gr-im — APPROVED** [review]

**Comment by gr-im** [comment]
Thank you very much ! 
@xvw may I ask for a deployment?

**Pull request merged**
